s = input().strip()
sub1, sub2 = s.split(',')
print(len(sub1) > len(sub2))
print(sub1 == sub2)
print(sub2.find(sub1) != -1)
s = input().strip()
print(s.strip())
print(len(s))
print(s.lower())
print(s.replace('a', '@'))
print(s.istitle())
s = input().strip()
print(s[1:-1])
print(s[1::2])
print(s[::-1].swapcase())
nums = list(map(int, input().strip().split()))
sorted_nums = sorted(nums)
print(sorted_nums)
print(sum(nums))
print(min(nums), max(nums))
s = input().strip()
lower_s = s.lower()
no_spaces = s.replace(' ', '')
print((lower_s == lower_s[::-1]) and (s == no_spaces))
n = int(input().strip())
hex_str = hex(n)[2:]
print(hex_str)
print(len(hex_str))
print('a' in hex_str)
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
n = int(input().strip())
print(months[n-1])